---
- hosts: all
  tasks:
    - name: Install Docker
      become: yes
      pacman:
        name:
          - docker

    - name: Create Docker user group
      become: yes
      group:
        name: docker
        state: present

    - name: Add current user to Docker group
      become: yes
      user:
        name: "{{ ansible_env['USER'] }}"
        create_home: no
        append: yes
        groups:
          - docker
