---
- hosts: all
  tasks:
    - name: Install repository dependencies
      become: yes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: Add Docker GPG key
      become: yes
      shell: curl --fail --silent --show-error --location https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      args:
        warn: no

    - name: Determine OS version name
      shell: lsb_release --codename --short
      register: os_name

    - name: Add docker repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_name.stdout }} stable
        filename: docker
        state: present

    - name: Install Docker
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Create Docker user group
      become: yes
      group:
        name: docker
        state: present

    - name: Add current user to Docker group
      become: yes
      user:
        name: "{{ ansible_env['USER'] }}"
        create_home: no
        append: yes
        groups:
          - docker
