---
- hosts: all
  tasks:
    - name: Add NeoVim PPA repository for latest version of NeoVim
      become: yes
      apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present
      when:
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install NeoVim
      become: yes
      apt:
        name:
          - git
          - make
          - neovim
        update_cache: yes
      when:
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install dependencies
      become: yes
      pacman:
        name:
          - git
          - make
          - neovim
        update_cache: yes
      when:
        - ansible_facts['distribution'] == 'Archlinux'

    - name: Install LunarVim configuration
      shell: curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh | bash -s - -- --no-install-dependencies

    - name: Add custom LunarVim configuration
      file:
        src: "{{ playbook_dir }}/../../lvim/config.lua"
        dest: ~/.config/lvim/config.lua
        state: link
        force: yes
