---
- hosts: all
  tasks:
    - name: Add NeoVim PPA repository for latest version
      become: yes
      apt_repository:
        repo: ppa:neovim-ppa/stable
        state: present

    - name: Install NeoVim
      become: yes
      apt:
        name:
          - build-essential
          - cmake
          - exuberant-ctags
          - git
          - neovim
          - python
          - python-dev
        update_cache: yes

    - name: Setup NeoVim configuration
      file:
        src: "{{ playbook_dir }}/../../nvim"
        dest: ~/.config/nvim
        state: link

    - name: Install NeoVim plugins
      shell: nvim +PackerInstall +qall
