---
- hosts: all
  tasks:
    - name: Install NeoVim
      become: yes
      pacman:
        name:
          - cmake
          - ctags
          - git
          - neovim
          - python-pynvim
        update_cache: yes

    - name: Setup NeoVim configuration
      file:
        src: "{{ playbook_dir }}/../../nvim"
        dest: ~/.config/nvim
        state: link

    - name: Install NeoVim plugins
      shell: nvim +PackerInstall +qall
