---
- hosts: all
  tasks:
    - name: Install NeoVim
      become: yes
      apt:
        name:
          - build-essential
          - cmake
          - exuberant-ctags
          - git
          - neovim
        update_cache: yes

    - name: Configure NeoVim
      file:
        path: ~/.config/nvim
        src: "{{ playbook_dir }}/../../nvim"
        force: true
        state: link

    - name: Install NeoVim plugins
      shell: nvim +PlugInstall +qall

    - name: Build YouCompleteMe for NeoVim
      shell: "./install.py {{ completers | join(' ') }}"
      args:
        chdir: ~/.config/nvim/plugged/YouCompleteMe
