---
- hosts: all
  tasks:
    - name: Install NeoVim
      become: yes
      apt:
        name:
          - build-essential
          - cmake
          - exuberant-ctags
          - git
          - neovim
          - python
          - python-dev
        update_cache: yes

    - name: Create NeoVim config directory
      file:
        path: ~/.config/nvim
        state: directory

    - name: Copy core NeoVim config
      copy:
        src: "{{ playbook_dir }}/../../nvim/init.vim"
        dest: ~/.config/nvim/init.vim
        force: yes

    - name: Copy autoload directory
      copy:
        src: "{{ playbook_dir }}/../../nvim/autoload"
        dest: ~/.config/nvim/
        force: yes

    - name: Copy filetype directory
      copy:
        src: "{{ playbook_dir }}/../../nvim/ftplugin"
        dest: ~/.config/nvim/
        force: yes

    - name: Copy plugin directory
      copy:
        src: "{{ playbook_dir }}/../../nvim/plugin"
        dest: ~/.config/nvim/
        force: yes

    - name: Install NeoVim plugins
      shell: nvim +PlugInstall +qall

    - name: Build YouCompleteMe for NeoVim
      shell: "./install.py {{ completers | join(' ') }}"
      args:
        chdir: ~/.config/nvim/plugged/YouCompleteMe
