---
- hosts: all
  vars:
    gotop_version: "3.0.0"
  tasks:
    - name: Install operational tools
      become: yes
      apt:
        name:
          - htop
          - lm-sensors
          - tmux
          - tree
        update_cache: yes

    - name: Setup Tmux configuration
      file:
        src: "{{ playbook_dir }}/../../tmux/tmux.conf"
        path: ~/.tmux.conf
        state: link

    - name: Check if gotop is installed
      shell: test "$(dpkg-query --show gotop 2> /dev/null | sed 's/gotop\s*//')" = '3.0.0'
      #shell: test $(dpkg-query --show gotop | sed 's/gotop\s*//') = {{ gotop_version }}
      register: gotop_check_deb
      failed_when: gotop_check_deb.rc > 1
      changed_when: gotop_check_deb.rc == 1

    - name: Remove old versions of gotop
      become: yes
      apt:
        name: gotop
        state: absent
      when: gotop_check_deb.rc == 1

    - name: Download gotop
      get_url:
        url: https://github.com/cjbassi/gotop/releases/download/3.0.0/gotop_3.0.0_linux_amd64.deb
        dest: /tmp/gotop.deb
      when: gotop_check_deb.rc == 1

    - name: Install gotop
      become: yes
      apt:
        deb: /tmp/gotop.deb
      when: gotop_check_deb.rc == 1
