---
- hosts: all
  vars:
    gotop_version: "4.1.3"
  tasks:
    - name: Install operational tools
      become: yes
      apt:
        name:
          - htop
          - lm-sensors
          - tmux
          - tree
        update_cache: yes
      when:
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install operational tools
      become: yes
      pacman:
        name:
          - htop
          - lm_sensors
          - tmux
          - tree
        update_cache: yes
      when:
        - ansible_facts['distribution'] == 'Archlinux'

    - name: Install gotop from AUR
      kewlfft.aur.aur:
        name: gotop-bin
        state: present
      when:
        - ansible_facts['distribution'] == 'Archlinux'

    - name: Setup Tmux configuration
      file:
        src: "{{ playbook_dir }}/../../tmux/tmux.conf"
        path: ~/.tmux.conf
        state: link

    - name: Download gotop
      get_url:
        url: https://github.com/xxxserxxx/gotop/releases/download/v{{ gotop_version }}/gotop_v{{ gotop_version }}_linux_amd64.deb
        dest: /tmp/gotop.deb
      when:
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install gotop
      become: yes
      apt:
        deb: /tmp/gotop.deb
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
