---
- hosts: all
  tasks:
    - name: Install operational tools
      become: yes
      apt:
        name:
          - htop
          - tmux
        update_cache: yes

    - name: Install sensor monitoring
      become: yes
      shell: "snap install sensors-unity && snap connect sensors-unity:hardware-observe :hardware-observe"

    - name: Setup Tmux configuration
      file:
        src: "{{ playbook_dir }}/../../tmux/tmux.conf"
        path: ~/.tmux.conf
        state: link
