---
- hosts: all
  tasks:
    - name: Install Zsh
      become: yes
      apt:
        name:
          - dconf-cli
          - font-manager
          - git
          - python-pygments
          - unzip
          - zsh
        update_cache: yes

    - name: Check current user
      shell: whoami
      register: username

    - name: Check current shell
      shell: "getent passwd $USER | cut --delimiter=: --fields=7"
      register: current_shell

    - name: Set default shell to Zsh
      become: yes
      shell: "chsh --shell $(which zsh) {{ username.stdout }}"
      when: current_shell.stdout != '/usr/bin/zsh'

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh

    - name: Configure Zsh
      file:
        path: ~/.zshrc
        src: "{{ playbook_dir }}/../../zsh/zshrc"
        force: true
        state: link

    - name: Install patched font
      become: yes
      shell: "{{ playbook_dir }}/../../zsh/install_font.sh"
      args:
        creates: "/usr/local/share/fonts/NerdFonts/Inconsolata Nerd Font Complete.otf"

    - name: Check for terminal profile
      shell: "{{ playbook_dir }}/../../zsh/is_theme_configured.sh"
      register: has_profile

    - name: Create terminal profile
      shell: "{{ playbook_dir }}/../../zsh/create_solarized_theme.sh"
      when: has_profile.stdout != 'true'

