---
- hosts: all
  tasks:
    - name: Install Zsh (Ubuntu)
      become: yes
      apt:
        name:
          - dconf-cli
          - font-manager
          - git
          - python-pygments
          - unzip
          - zsh
        update_cache: yes
      when:
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install Zsh (Manjaro)
      become: yes
      pacman:
        name:
          - git
          - python-pygments
          - unzip
          - zsh
        update_cache: yes
      when:
        - ansible_facts['distribution'] == 'Archlinux'

    - name: Set default shell to Zsh
      become: yes
      user:
        name: "{{ ansible_env['USER'] }}"
        create_home: no
        shell: /usr/bin/zsh

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        executable: /usr/bin/zsh
        creates: ~/.oh-my-zsh

    - name: Configure Zsh
      file:
        path: ~/.zshrc
        src: "{{ playbook_dir }}/../../zsh/zshrc"
        force: true
        state: link

    - name: Install patched font
      become: yes
      shell: "{{ playbook_dir }}/../../zsh/install_font.sh"
      args:
        creates: "~/.local/share/fonts/NerdFonts/Sauce Code Pro Nerd Font Complete.ttf"

    - name: Download Zsh theme
      git:
        repo: https://github.com/durandj/remotely-amused.git
        dest: ~/.oh-my-zsh/custom/themes/remotely-amused

    - name: Setup Zsh theme
      file:
        src: ~/.oh-my-zsh/custom/themes/remotely-amused
        path: ~/.oh-my-zsh/custom/themes/remotely-amused.zsh-theme
        state: link

    - name: Check for terminal profile
      shell: "{{ playbook_dir }}/../../zsh/is_theme_configured.sh"
      register: has_profile

    - name: Create terminal profile
      shell: "{{ playbook_dir }}/../../zsh/create_solarized_theme.sh"
      when: has_profile.stdout != 'true'

    - name: Add commands for managing secrets
      become: yes
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: "{{ playbook_dir }}/../../zsh/create-secret"
          dest: /usr/local/bin
        - src: "{{ playbook_dir }}/../../zsh/get-secret"
          dest: /usr/local/bin
        - src: "{{ playbook_dir }}/../../zsh/delete-secret"
          dest: /usr/local/bin
