#!/usr/bin/env bash

function has_secret_tools() {
    command -v secret-tool > /dev/null
}

function main() {
    if [[ $# < 2 ]]; then
        echo "usage: $0 <scope> <name>"
        exit 1
    fi

    if ! has_secret_tools; then
        echo "secret-tool is not installed but is required"
        echo "Please install libsecret and secret-tool"
        exit 1
    fi

    local scope="$1"; shift
    local secret_name="$1"; shift

    secret-tool lookup $scope $secret_name
}

main $@
